language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

env:
  - PHP_BIN=php
  - PHP_BIN=php-cgi

before_install:
  # turn off XDebug
  - phpenv config-rm xdebug.ini || return 0

install:
  - travis_retry composer install --no-progress --prefer-dist

script:
  - vendor/bin/tester -p $PHP_BIN tests -s

after_failure:
  # Print *.actual content
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

jobs:
  include:
    - name: Lowest Dependencies
      env: PHP_BIN=php
      install:
        - travis_retry composer update --no-progress --prefer-dist --prefer-lowest --prefer-stable


    - name: Lint
      install:
        - travis_retry composer create-project jakub-onderka/php-parallel-lint temp/php-parallel-lint --no-interaction --no-progress
      script:
        - php temp/php-parallel-lint/parallel-lint src


    - name: Code Checker
      script:
        - vendor/bin/phpcs --standard=psr12 src


    - stage: Static Analysis (informative)
      install:
        - travis_retry composer install --no-progress --prefer-dist
      script:
        - vendor/bin/phpstan.phar analyse --level 7 src


    - stage: Code Coverage
      script:
        - vendor/bin/tester -p phpdbg tests -s --coverage ./coverage.xml --coverage-src ./src
      after_script:
        - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
        - php coveralls.phar --verbose --config tests/.coveralls.yml


  allow_failures:
    - stage: Static Analysis (informative)
    - stage: Code Coverage


sudo: false

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
